### ISSUE TITLE
40 Node GPU Cluster required??

### ISSUE THREAD

**Issue by Justmalhar** [xai-org/grok-1#172]

**Comment by AndreSlavescu** [comment]
Exactly 8 GPUs are required due to the mesh shape assertion (1, 8). To run at native size, you will likely need 8x80GB GPUs (A100 80GB / H100GB). I think with HIP, you can also use AMD GPUs and translate the compiled CUDA to ROCm. The MI200 series will likely be needed to meet the VRAM spec for mixed precision.

**Comment by trholding** [comment]
Request you to move to this discussions thread here: https://github.com/xai-org/grok-1/discussions/183

Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
https://github.com/xai-org/grok-1/issues/69
https://github.com/xai-org/grok-1/issues/108
