### ISSUE TITLE
Unable to view Tokenizer.model 

### ISSUE THREAD

**Issue by Dharmyouddh3102** [xai-org/grok-1#178]
Says it is too big, which app should I open it with?

**Comment by trholding** [comment]
Technically this is not a issue or bug. 

tokenizer.model is used by run.py / runners.py, inference requires both the tokenizer / vocab and checkpoints. These files are binary and if you open them with any application you'd not be able open due to file size or you'd see garbled characters and text. You could use a hex editor to see values but you'd not able to gain any insight. Instead to to dump the contents you'd need to write a python script that uses sentencepiece to dump the contents.

Ref: https://github.com/xai-org/grok-1/blob/d6d9447e2d3c9bd81da571dc8681ea60009e4c03/runners.py#L288

---
Please close this issue and move to:

https://github.com/xai-org/grok-1/discussions

Reason:
https://github.com/xai-org/grok-1/issues/69
https://github.com/xai-org/grok-1/issues/108
