### ISSUE TITLE
Should the version of jax in requirements.txt be cuda12-pip instead of cuda12_pip?

### ISSUE THREAD

**Issue by zhangjh** [xai-org/grok-1#186]
run `pip install -r requirements.txt` failed, replaced it as `cuda12-pip` successed.

**Comment by trholding** [comment]
Are you using Mac?

**Comment by trholding** [comment]
Jax issue. Unconfirmed Possible solutions:

### Linux/Win:
```
pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install -r requirements.txt
```

### Mac:
```
pip install -U "jax[cuda12-pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install -r requirements.txt
```
Ref:  
https://github.com/xai-org/grok-1/issues/186#issue-2194091076
https://github.com/xai-org/grok-1/issues/24#issuecomment-2002687351

Solution of / Related to / Duplicate of:
https://github.com/xai-org/grok-1/issues/173
https://github.com/xai-org/grok-1/issues/143
https://github.com/xai-org/grok-1/issues/106
https://github.com/xai-org/grok-1/issues/104
https://github.com/xai-org/grok-1/issues/102
https://github.com/xai-org/grok-1/issues/83
https://github.com/xai-org/grok-1/issues/82
https://github.com/xai-org/grok-1/issues/24
https://github.com/xai-org/grok-1/issues/6

Please report what works for you on what OS (Mac/Win/WSL/Linux/?BSD) so that we can come to a conclusion to this problem.

**Comment by zhangjh** [comment]
yes, on mac must use jax[cuda12-pip]

**Comment by AlberHu** [comment]
> run `pip install -r requirements.txt` failed, replaced it as `cuda12-pip` successed.

It works on my Win PC, thanks a lot!
